### ISSUE TITLE
VK_KHR_create_renderpass2 raises Fossilize ERROR

### ISSUE THREAD

**Issue by FilippoLeon** [ValveSoftware/Fossilize#111]
Is more a question than a bug (probably), but since I have enabled and used renderpass2, I obtain some fossilize error for my renderpasses handles:
> Fossilize ERROR: Render pass handle 0xe706cb000002d9d3 is not registered. It has either not been recorded, or it failed to be recorded earlier.

Am I doing something wrong or is not supported at the moment? Is there a way to silence the error?

**Comment by HansKristian-Work** [comment]
It's a known missing feature, hasn't been prioritized since noone have been using it. Do games actually use this now?
