### ISSUE TITLE
Steam leaks fossilize_replay children in stopped state

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/Fossilize#129]
When Steam crashes (and maybe also when quit normally) while fossilze_replay is running, it may leak fossilize_replay processes in stopped state (as part of the load limiter which `SIG_STOP`s children). The main process should probably send `SIG_CONT` to all children before exiting or being forcefully quit.

**Comment by HansKristian-Work** [comment]
They should receive SIGKILL. Is SIGKILL ignored for stopped processes?

**Comment by kakra** [comment]
It seems so: If I manually send SIGKILL to those, nothing happens until I send SIGCONT, and then those processes will instantly die if I sent SIGKILL previously. This is probably because SIGSTOP can be used for debugging: It stops the process, and won't get any more CPU cycles, thus it probably also doesn't receive the signal.

The comments in [this question](https://unix.stackexchange.com/questions/209288/why-doesnt-sigkill-terminate-a-stopped-program-yes) seem to suggest that you need to send SIGCONT so the SIGKILL signal sent previously can be received. After all, the process isn't killed from the outside, it will kill itself when it receives the signal.

Usually, SIGKILL should still kill the process because this signal cannot be blocked. But [this answer](https://unix.stackexchange.com/a/209331/2035) suggests that - if you stop the process while in a kernel context - SIGKILL won't be delivered until it returns, so a SIGCONT would be needed. Maybe that's what happens? The other answers suggest that this can't properly tested or investigated from the shell.

Here's another link: https://unix.stackexchange.com/questions/298644/why-cant-i-kill-a-sigstopd-process-with-a-sigterm-and-where-is-the-pending-si/298650

The conclusion seems to be somewhat odd, some suggest that SIGKILL should kill a stopped process, others say it doesn't, and all the tests seem to confirm the first which some attribute to a bash bug. It looks like it is: Stopped processes cannot kill themselves until they continue.

**Comment by HansKristian-Work** [comment]
the higher level used SIGTERM instead of KILL which broke it. Another bug was that socketpair DGRAM doesn't work like I expected :V
