### ISSUE TITLE
[question] why fossilize running? 

### ISSUE THREAD

**Issue by mandaputtra** [ValveSoftware/Fossilize#138]
When I open steam, it opens `fossilize_repla` on my machine, it eats about 30% CPU. But when I close steam, it is still running. Why is that? What trigger Fossilize to run? How do fossilize operate? I want to know this because it seems it run on its own,

**Comment by kakra** [comment]
This is the background shader pre-caching of Steam. It is designed to operate on idle CPU power only, and it will use only a few CPU cores in background, so it should not hurt. It may stay running for a short time when you start a game or quit Steam.

If you want to disable it, you can disable shader pre-caching in the Steam options. But this may introduce micro-stuttering in games then.

**Comment by mandaputtra** [comment]
Thanks! yes it actually stopped after 3 hours.
