### ISSUE TITLE
wishlist feature: pipeline compile timing output

### ISSUE THREAD

**Issue by zmike** [ValveSoftware/Fossilize#216]
I want to be able to extract a pipeline that takes a long time to compile from a foz file. Currently I have to do something like

`for x in $(fossilize-list --tag 6 file.foz); do fossilize-replay --pipeline-hash $x file.foz ;done`

and iterate over all of them with in-driver printfs to check the timing. It would be more convenient if fossilize could provide this sort of timing, or maybe output a list of slowest compiles?

**Comment by HansKristian-Work** [comment]
Resolved on master.
