### ISSUE TITLE
Setting fossilize environment for steam games

### ISSUE THREAD

**Issue by Trayshar** [ValveSoftware/Fossilize#236]
Setting any of the `FOSSILIZE` environment variables documented in the [Readme](https://github.com/ValveSoftware/Fossilize#linuxwindows) either with export or directly  in a steam games launch options doesn't seem to do anything.

Apparently they have to be prefixed with `STEAM_` like so: `STEAM_FOSSILIZE=1 STEAM_FOSSILIZE_DUMP_PATH=/my/custom/path STEAM_FOSSILIZE_DUMP_SYNC=1`. Putting that into the game's launch options worked.

I wasn't able to find any documentation on this. Is this behaviour intended?

**Comment by HansKristian-Work** [comment]
The layer shipped in steam uses different environment variables. To use FOSSILIZE=1 you're supposed to install your own custom built layer. You're not supposed to override Steam's variables here.

**Comment by Trayshar** [comment]
Ok, thank you for explaining!
