### ISSUE TITLE
REQUEST: Allow shader cache download per game

### ISSUE THREAD

**Issue by Randy28CR** [ValveSoftware/Fossilize#260]
Hello!
I would like to prise how great this is to prevent shader compilation stutter on games that normally have it on Windows.
I have tested games like Ghostrunner 2, Final Fantasy VII Remake, Persona 3 Reload, Marvel Guardians of the Galaxy and thanks to Fossilize those games do not stutter at all on Linux. Thank you so much for building something that actually faces the shader compilation stutter issue on PC. 
However, thanks to the GPL addition, most DX11 games do not stutter anymore. Besides, I have found that DX11 games are the ones with longer size Shader cache files.
With Proton Experimental, the amount of downloads of Shaders per day get increased, which is insane. In my opinion, it get annoying.
I think it would be great if you provide us an option to download Shaders per game and a sort of shader update schedule, so we can decide whether we update them manually or on a daily, weekly or monthly basis.
I know this might be asking for too much, however, this feature is very cool but it is being affected by some annoying stuff. 
I do believe this is an important step to make Steam OS way more atractive. 

In the meantime, what I have done is turning off the precaching system, put games to update only when launched (I have to do it game by game, which is annoying) and when there is a game that I know will stutter, I turn on the shader pre cache system so Steam only downloads the shaders of that game. Then I start the game, shaders processes and then go back to desktop mode and then turn off shader precaching. 
As you can imagine, this is not practical at all. I could just select "download shaders for this game" or "keep shaders update every (day/ week/month).

I have done all of this through Bazzite on my ROG Ally but I am planning to upgrade my RTX 3070 to next AMD GPU only for Bazzite (And official Steam OS when it is ready for desktops).

Please, take this feedback into account!

**Comment by kisak-valve** [comment]
Hello @Randy28CR, this is a request for the Steam client, not fossilize, and the request is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6486.

Closing as a duplicate.
