### ISSUE TITLE
Multiview

### ISSUE THREAD

**Issue by JoshKlint** [ValveSoftware/Fossilize#53]
When using a VkRenderPassMultiviewCreateInfo object in VkRenderPassCreateInfo::pNext I get the following error:

> Fossilize ERROR: Error: pNext in VkRenderPassCreateInfo not supported. (pNext->sType chain: [1000053000])
Fossilize ERROR: Failed to record render pass.

Multiview is core in Vulkan 1.1, with a minimum of six passes supported:

Usage:
https://github.com/SaschaWillems/Vulkan/blob/master/examples/multiview/multiview.cpp
```
VkRenderPassMultiviewCreateInfo renderPassMultiviewCI = {};
if (layers > 1)
{
	uint32_t viewMask = 0;// 0b00111111;
	uint32_t correlationMask = 0;// 0b00111111;
	for (int n = 0; n < layers; ++n)
	{
		viewMask += pow(2, n);
		correlationMask += pow(2, n);
	}
	if (layers == 6) Assert(viewMask == 0b00111111);
	renderPassMultiviewCI.sType = VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO;
	renderPassMultiviewCI.subpassCount = 1;
	renderPassMultiviewCI.pViewMasks = &viewMask;
	renderPassMultiviewCI.correlationMaskCount = 1;
	renderPassMultiviewCI.pCorrelationMasks = &correlationMask;
	renderPassInfo.pNext = &renderPassMultiviewCI;
}
```

**Comment by HansKristian-Work** [comment]
There's generally a lot of pNext structures which aren't added yet, but doesn't hurt to add them.

**Comment by JoshKlint** [comment]
I didn't even know what Fossilize was until I saw this in our program's printed output while using the Steam overlay.

**Comment by HansKristian-Work** [comment]
Steam loads the Fossilize recording layer, but the multiview pNext structs were not recognized. Other than some error spam, there is no real issue to worry about. Once Steam pulls in latest master, this spam should go away.
