### ISSUE TITLE
Fossilize hangs indefinitely consuming CPU when compiling Spyro shaders

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/Fossilize#55]
Fossilize process hangs indefinitely on shader 2292/3859 (per shader_log.txt) when compiling shaders for steam appid 996580

Reproduction via Steam console:
`shader_build 996580 1`

Confirmed this on two different Nvidia systems, one running 440.43.01 Vk Dev drivers, other running 440.44 stable drivers.

**Comment by HansKristian-Work** [comment]
Reproduced on 435.27.08.

Hits the bug: https://developer.nvidia.com/vulkan-driver mentions:
"Fixed a bug that caused DXVK titles to endlessly loop during shader compilation if no OpSource instruction was present ". There is a SteamVR shader which gets compiled and hangs the driver.

I'll try to implement pipeline compilation timeouts and treat these pipelines as crashing instead.

**Comment by NoXPhasma** [comment]
Probably the same issue is with [Dirt Rally 2.0](https://store.steampowered.com/app/690790):

```
[2020-01-09 18:41:10] 4770/5961.
[2020-01-09 18:41:11] 4770/5961.
[2020-01-09 18:41:11] 4770/5961.
[2020-01-09 18:41:12] 4770/5961.
[2020-01-09 18:41:12] 4770/5961.
```

**Comment by HansKristian-Work** [comment]
Same issue in Dirt Rally indeed. Got timeout support working, and both archives can be played through with `--timeout-seconds` option.
