### ISSUE TITLE
Install on Windows missing VkLayer_fossilize.json

### ISSUE THREAD

**Issue by dzimanAMD** [ValveSoftware/Fossilize#61]
Install copies the files to:
C:\Program Files (x86)\Fossilize\lib\VkLayer_fossilize.dll
C:\Program Files (x86)\Fossilize\lib\VkLayer_fossilize.lib

The json file, VkLayer_fossilize.json, for the layer is not copied.

**Comment by HansKristian-Work** [comment]
Installing the layer on Windows is a bit awkward since you technically need to mess around with the registry (not happening), so the half-way solution is to just place the json along the DLL.
