### ISSUE TITLE
vkGetInstanceProcAddr and vkGetDeviceProcAddr return wrong functions

### ISSUE THREAD

**Issue by yNeo** [ValveSoftware/Fossilize#78]
On Linux, when calling your vkGetInstanceProcAddr with vkGetInstanceProcAddr(instance, "vkGetInstanceProcAddr"), instead of returning itself (as it should) it returns the loader's global vkGetInstanceProcAddr (same for vkGetDeviceProcAddr). This in turn can cause layers above you to get incorrect function pointers which can crash the application.

The reason this is happening is that your vkGetInstanceProcAddr function is defined with that exact name and with process global linkage, which means that in line 354 in dispatch.cpp, the symbol 'vkGetInstanceProcAddr' does not refer to your function, but to the process global one.
Because the loader is loaded before your layer, the global function will just be the loader's one instead of yours.

To fix this, I recommend renaming your functions to something like Fossilize_GetInstanceProcAddr and Fossilize_GetDeviceProcAddr, and adding the following field in the .json file inside the "layer" section:
```
"functions": {
      "vkGetInstanceProcAddr": "Fossilize_GetInstanceProcAddr",
      "vkGetDeviceProcAddr": "Fossilize_GetDeviceProcAddr"
}
```

Cheers

**Comment by HansKristian-Work** [comment]
Thanks for the report, no vk* symbols should be exported now.
