### ISSUE TITLE
Fossilize reprocesses the same shaders over and over again (Warframe)

### ISSUE THREAD

**Issue by jnines** [ValveSoftware/Fossilize#98]
> OS: Arch Linux
> CPU: 3700X
> GPU: GTX 1070 (455.28)
> RAM: 16GB

Steam will continually reprocess Warframe shaders.  If I let it finish (viewed from `Settings - Shader Pre-Caching`), start and close the game, it will start processing again.  If I restart the system, it will again reprocess the shaders.  The only tip I've read to fix this is to change the default game directory to the same that Warframe is installed in.  I've done this, however it hasn't changed anything.

Each time this takes around 20-25 minutes, and a not-insignificant amount of memory, as well as unneeded wear on my M.2.  Is there a way I can fix this without totally disabling Shader Pre-Caching?

**Comment by kisak-valve** [comment]
Hello @jnines, when Steam runs Fossilize is managed by the Steam client, not Fossilize itself, and this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7306. Closing as a duplicate.
